### ISSUE TITLE
Omit some viewer components

### ISSUE THREAD

**Issue by MFarejowicz** [davidhoksza/MolArt#11]
I'm planning to use the MolArt viewer in a web app I'm developing. I'm trying to get it so that a user is only viewing one specific PDB entry on a page. I've set the `pdbIds` list to just be that one entry, so it indeed only shows the one entry. 

As such, the dropdown pictured here is now obsolete. 

<img width="890" alt="Screen Shot 2020-03-04 at 5 57 57 PM" src="https://user-images.githubusercontent.com/10686713/75931138-3fd50900-5e42-11ea-9602-ae6a959ba9da.png">
I was wondering if there was any way to get rid of it?

Thanks so much!

**Comment by davidhoksza** [comment]
If you are passing the pdbIds by yourself and you know, there will be only one record, a quick workaround would be to simply hide the two combo boxes by calling `$('.lm-list').hide()` from JavaScript. 

Currently, I am off the grid and will implement this functionality in about two weeks from now. So if you are really in a hurry, you can use the dirty way mentioned above, otherwise, this is just to acknowledge your request and let you know that I will implement this feature soon.

**Comment by MFarejowicz** [comment]
That's pretty smart. 

The workaround is good enough for me. Thanks for the quick response, and don't worry too much about getting it formally implemented.
